### ISSUE TITLE
Document-level dataset

### ISSUE THREAD

**Issue by LinasVidziunas** [nanda-rani/TTPHunter-Automated-Extraction-of-Actionable-Intelligence-as-TTPs-from-Narrative-Threat-Reports#1]
Thank you for sharing the code associated with your paper. I appreciate your efforts in making the resources available to the community. However, I noticed that the document-level annotated dataset mentioned in the paper is missing from the repository.

Could you please provide access to this dataset or specify the sources from which it was compiled? This would be of great help to our ongoing research.

**Comment by nanda-rani** [comment]
The report's information was gathered from various fragmented sources, primarily threat reports from security firms. However, you can find recent TRAM data, published by MITRE last year, [here](https://github.com/center-for-threat-informed-defense/tram/tree/main).
